z511:
  skeltype: panoptic15
  cam: '09'
  keyframes: []
  camera_mode: 'set'
  camera_keyframe:
    60: # 表示过渡的帧数
    # 手动在blender里找一个好的角度
      rotation: [40, 0, -54]
      location: [-2, -1.4, 3.3]
  camera_root: '/Users/shuaiqing/nas/ZJUMoCap/DeepMocap/230511/558-balance'
  res: [1024, 1024]
  light:
    - location: [0, -1, 1]
      rotation: [0., 30, 0]
      strength: 10.
  add_ground: True
  add_wall: False
  format: 'PNG'
  color_table: [
      [8, 76, 97, 255], # blue
      [219, 58, 52, 255], # red
  ]
z558:
  skeltype: panoptic15
  cam: '09'
  keyframes: [319]
  camera_mode: 'set'
  camera_keyframe:
    30: # 表示过渡的帧数
    # 手动在blender里找一个好的角度
      rotation: [62, 0, 0]
      location: [0.58, -2.9, 2.0]
    60: # 表示过渡的帧数
    # 手动在blender里找一个好的角度
      rotation: [62, 0, 90]
      location: [3, 0, 2.0]
    90: # 表示过渡的帧数
    # 手动在blender里找一个好的角度
      rotation: [62, 0, 180]
      location: [0.62, 3, 2.0]
    115:
      rotation: [62, 0, 240]
      location: [-2, 2.3, 2.0]
    final: stop
  camera_root: '/Users/shuaiqing/nas/ZJUMoCap/DeepMocap/230511/558-balance'
  res: [1024, 1024]
  light:
    - location: [0, -1, 1]
      rotation: [0., 30, 0]
      strength: 10.
  add_ground: True
  add_wall: False
  format: 'PNG'
  color_table: [
      [8, 76, 97, 255], # blue
      [219, 58, 52, 255], # red
  ]
